"""id error

Revision ID: 3206632167df
Revises: 7a036fc2ab5f
Create Date: 2024-02-03 18:58:54.626130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3206632167df'
down_revision = '7a036fc2ab5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
