"""still seeding

Revision ID: 7a036fc2ab5f
Revises: 80c920f52a36
Create Date: 2024-02-03 15:50:57.718048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a036fc2ab5f'
down_revision = '80c920f52a36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
