"""seeding...

Revision ID: 80c920f52a36
Revises: 81925b1b3e24
Create Date: 2024-02-03 15:47:26.357554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80c920f52a36'
down_revision = '81925b1b3e24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
